Kusumgar/Models/CRM/ComplaintViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KusumgarBusinessEntities;

using KusumgarBusinessEntities.Common;


namespace Kusumgar.Models
{
    public class ComplaintViewModel
    {
        public ComplaintInfo Complaint { get; set; }
        public List<ComplaintInfo> Complaints { get; set; }
        public PaginationInfo Pager { get; set; }
        public List<FriendlyMessageInfo> Friendly_Message { get; set; }
        public Complaint_Filter Filter { get; set; }
        public int Complaint_Id { get; set; }

        public string Lot_No { get; set; }

        public ComplaintViewModel()
        {
            Complaint = new ComplaintInfo();
            Complaints = new List<ComplaintInfo>();
            Pager = new PaginationInfo();
            Friendly_Message = new List<FriendlyMessageInfo>();
            Filter = new Complaint_Filter();
        }
        
    }
    
    public class Complaint_Filter
    {
        public string Customer_Name { get; set; }
        public int Customer_Id { get; set; }
    }
}

Kusumgar/Models/CRM/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KusumgarBusinessEntities;

using KusumgarBusinessEntities.Common;


namespace Kusumgar.Models
{
    public class ContactViewModel
    {
        public ContactViewModel()
        {
            Contacts = new List<ContactInfo>();

            Contact = new ContactInfo();

            Customer_Contact_Types = new List<CustomerContactTypeInfo>();

            Friendly_Message = new List<FriendlyMessageInfo>();

            Pager = new PaginationInfo();

            Filter = new Contact_Filter();
        }

        public List<ContactInfo> Contacts{ get; set; }

        public ContactInfo Contact { get; set; }

        public List<CustomerContactTypeInfo> Customer_Contact_Types { get; set; }

        public List<FriendlyMessageInfo> Friendly_Message { get; set; }

        public PaginationInfo Pager { get; set; }

        public Contact_Filter Filter { get; set; }
    }

    public class Contact_Filter
    {
        public int Customer_Id { get; set; }

        public string Customer_Name { get; set; }
    }
}

Kusumgar/Models/CRM/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KusumgarBusinessEntities;

using KusumgarBusinessEntities.Common;


namespace Kusumgar.Models
{
    public class CustomerViewModel
    {
        public CustomerViewModel()
        {
            Customers = new List<CustomerInfo>();

            Customer = new CustomerInfo();

            Friendly_Message = new List<FriendlyMessageInfo>();

            Pager = new PaginationInfo();

            States = new List<StateInfo>();

            Nations = new List<NationInfo>();

            Filter = new CustomerFilter();
        }

        public List<CustomerInfo> Customers { get; set; }

        public CustomerInfo Customer { get; set; }

        public List<FriendlyMessageInfo> Friendly_Message { get; set; }

        public PaginationInfo Pager { get; set; }

        public List<StateInfo> States { get; set; }

        public List<NationInfo> Nations { get; set; }

        public CustomerFilter Filter { get; set; }

    }

    public class CustomerFilter
    {
        public string Customer_Name { get; set; }

        public int Customer_Id { get; set; }

        public string Email { get; set; }

        public string Turnover { get; set; }

        public int Nation_Id { get; set; }

        public int Status_Id { get; set; }

        public int State_Id { get; set; }

        public string Pin_Code { get; set; }
        
    }
}

Kusumgar/Controllers/PostLogin/CRM/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kusumgar.Models;
using KusumgarBusinessEntities;

using KusumgarModel;
using KusumgarBusinessEntities.Common;
using KusumgarHelper.PageHelper;
using KusumgarCrossCutting.Logging;
using System.Web.Security;


namespace Kusumgar.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Customer/

        public ContactManager _contactMan;
        public CustomerManager _customerMan;

        public ContactController()
        {
            _contactMan = new ContactManager();
            _customerMan = new CustomerManager();
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Create)]

        public ActionResult Index(ContactViewModel cViewModel)
        {
            ViewBag.Title = "KPCL ERP :: Create, Update";
            PaginationInfo pager = new PaginationInfo();
            try
            {
                cViewModel.Customer_Contact_Types = _customerMan.Get_Customer_Contact_Type_By_Id(cViewModel.Contact.Customer_Id);
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Index " + ex.ToString());
            }

            return View("Index", cViewModel);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Search)]

        public ActionResult Search(ContactViewModel cViewModel)
        {
            

            ViewBag.Title = "KPCL ERP :: Search";

            try
            {

            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Search " + ex.ToString());
            }

            return View(cViewModel);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Create)]

        public JsonResult Insert(ContactViewModel cViewModel)
        {
            try
            {
                cViewModel.Contact.CreatedBy = ((UserInfo)Session["User"]).UserId;

                cViewModel.Contact.UpdatedBy = ((UserInfo)Session["User"]).UserId;

                cViewModel.Contact.CreatedOn = DateTime.Now;

                cViewModel.Contact.UpdatedOn = DateTime.Now;

                cViewModel.Contact.Contact_Id = _contactMan.Insert_Contact(cViewModel.Contact);

                cViewModel.Friendly_Message.Add(MessageStore.Get("CO001"));
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Insert " + ex.ToString());
            }

            return Json(cViewModel);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Edit)]

        public JsonResult Update(ContactViewModel cViewModel)
        {
            try
            {
                cViewModel.Contact.UpdatedBy = ((UserInfo)Session["User"]).UserId;

                cViewModel.Contact.UpdatedOn = DateTime.Now;

                _contactMan.Update_Contact(cViewModel.Contact);

                cViewModel.Friendly_Message.Add(MessageStore.Get("CO002"));
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Update " + ex.ToString());
            }

            return Json(cViewModel);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Create)]

        public JsonResult Insert_Contact_Custom_Fields(ContactViewModel cViewModel)
        {
            try
            {
                cViewModel.Contact.Custom_Fields.CreatedBy = ((UserInfo)Session["User"]).UserId;

                cViewModel.Contact.Custom_Fields.UpdatedBy = ((UserInfo)Session["User"]).UserId;

                cViewModel.Contact.Custom_Fields.CreatedOn = DateTime.Now;

                cViewModel.Contact.Custom_Fields.UpdatedOn = DateTime.Now;

                _contactMan.Insert_Contact_Custom_Fields(cViewModel.Contact.Custom_Fields);

                cViewModel.Contact = _contactMan.Get_Contact_By_Id(cViewModel.Contact.Custom_Fields.Contact_Id);

                cViewModel.Friendly_Message.Add(MessageStore.Get("CO003"));
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Insert_Contact_Custom_Fields " + ex.ToString());
            }

            return Json(cViewModel);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Create)]

        public JsonResult Update_Contact_Custom_Fields(ContactViewModel cViewModel)
        {
            try
            {
                cViewModel.Contact.Custom_Fields.UpdatedBy = ((UserInfo)Session["User"]).UserId;

                cViewModel.Contact.Custom_Fields.UpdatedOn = DateTime.Now;

                _contactMan.Update_Contact_Custom_Fields(cViewModel.Contact.Custom_Fields);

                cViewModel.Contact = _contactMan.Get_Contact_By_Id(cViewModel.Contact.Custom_Fields.Contact_Id);

                cViewModel.Friendly_Message.Add(MessageStore.Get("CO004"));
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Update_Contact_Custom_Fields " + ex.ToString());
            }

            return Json(cViewModel);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Search)]

        public JsonResult Get_Contact_List(ContactViewModel cViewModel)
        {
            PaginationInfo pager = new PaginationInfo();

            try
            {
                pager = cViewModel.Pager;

                if (cViewModel.Filter.Customer_Id != 0)
                {
                    cViewModel.Contacts = _contactMan.Get_Contacts_By_Name(cViewModel.Filter.Customer_Id, ref pager);
                }
                else
                {

                    cViewModel.Contacts = _contactMan.Get_Contacts(ref pager);
                }

                cViewModel.Pager.PageHtmlString = PageHelper.NumericPager("javascript:PageMore({0})", cViewModel.Pager.TotalRecords, cViewModel.Pager.CurrentPage + 1, cViewModel.Pager.PageSize, 10, true);
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Get_Contact_List " + ex.ToString());
            }
            finally
            {
                pager = null;
            }

            return Json(cViewModel);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Edit)]

        public ActionResult Get_Contact_By_Id(ContactViewModel cViewModel)
        {
            try
            {
                cViewModel.Contact = _contactMan.Get_Contact_By_Id(cViewModel.Contact.Contact_Id);
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Get_Contact_By_Id " + ex.ToString());
            }

            return Index(cViewModel);
        }

        public JsonResult Get_Contact_Type_By_Customer_Id(int customer_Id)
        {
            List<CustomerContactTypeInfo> Customer_Contact_Types = new List<CustomerContactTypeInfo>();
            try
            {
                PaginationInfo pager = new PaginationInfo();
                pager.IsPagingRequired = false;
                Customer_Contact_Types = _customerMan.Get_Customer_Contact_Type_By_Id(customer_Id);
            }
            catch (Exception ex)
            {                
                Logger.Error("Contact Controller - Get_Contact_Type_By_Customer_Id " + ex.ToString());
            }
            return Json(Customer_Contact_Types, JsonRequestBehavior.AllowGet);
        }

        [AuthorizeUser(AppFunction.Customer_Contact_Edit)]

        public JsonResult Delete_Contact_Custom_Fields(int contact_Custom_Field_Id)
        {
            List<FriendlyMessageInfo> Friendly_Message = new List<FriendlyMessageInfo>();

            try
            {
                _contactMan.Delete_Contact_Custom_Fields(contact_Custom_Field_Id);

                Friendly_Message.Add(MessageStore.Get("CO005"));
            }
            catch (Exception ex)
            {
                Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Delete_Contact_Custom_Fields " + ex.ToString());
            }

            return Json(new { Friendly_Message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult View_Contact(ContactViewModel cViewModel)
        {
            ViewBag.Title = "KPCL ERP :: Search";

            try
            {
                cViewModel.Contact = _contactMan.Get_Contact_By_Id(cViewModel.Contact.Contact_Id);
            }
            catch(Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Search " + ex.ToString());
            }

            return View("View",cViewModel);
        }
     
        public PartialViewResult Printable_Contact(int contact_Id)
        {
            ViewBag.Title = "KPCL ERP :: Print";

            ContactViewModel cViewModel = new ContactViewModel();

            cViewModel.Contact.Contact_Id = contact_Id;

            try
            {
                cViewModel.Contact = _contactMan.Get_Contact_By_Id(cViewModel.Contact.Contact_Id);
            }
            catch (Exception ex)
            {
                cViewModel.Friendly_Message.Add(MessageStore.Get("SYS01"));

                Logger.Error("Contact Controller - Search " + ex.ToString());
            }

Kusumgar/Views/PostLogin/CRM/Contact/Search.cshtml
@model Kusumgar.Models.ContactViewModel
@using KusumgarBusinessEntities.Common

<script src="/Scripts/CRM/Event/contact_listing_event.js"></script>
<script src="/Scripts/CRM/Method/contact_listing_method.js"></script>
<style>
    .example-modal .modal {
        position: relative;
        top: auto;
        bottom: auto;
        right: auto;
        left: auto;
        display: block;
        z-index: 1;
    }

    .example-modal .modal {
        background: transparent!important;
    }
</style>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Contact
            <small>Search</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li>CRM</li>
            <li class="active">Contact search</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Customer Search -->
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- Custom Tabs -->
                <div class="nav-tabs-custom"> 
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab_1" data-toggle="tab">Search customer's contact</a></li>
                        @*<li><a href="#tab_2" data-toggle="tab">Search supplier's contact</a></li>*@
                        <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-info"></i></a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_1">
                            <form id="frmSearch_contact">
                                <input type="hidden" id="hdfCurrentPage" name="Pager.CurrentPage" value="@Model.Pager.CurrentPage" />
                                <input type="hidden" id="hdfContact_Id" name="contact.Contact_Id">
                                <input type="hidden" id="hdCustomer_Id" name="Customer.Customer_Id">
                                <br />
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="txtCustomerName">Customer name</label>
                                            <div class="auto-complete">
                                                <input type="text" class="form-control input-sm" id="txtCustomer_Name" placeholder="Enter customer name" value="">
                                                <input type="hidden" id="hdnCustomer_Id" value="@Model.Filter.Customer_Id"  name="Filter.Customer_Id" class="auto-complete-value">
                                                <input type="hidden" id="hdnCustomer_Name" value="@Model.Filter.Customer_Name" name="Filter.Customer_Name" class="auto-complete-label">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="box-footer">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="btn-group pull-left">
                                                <button type="button" id="btnSearch" class="btn btn-success btn-sm">Search</button>
                                                @*<button type="button" id="btnAdvanceSearch" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Advance Search</button>*@
                                                <a class="btn btn-primary btn-sm" href="@Url.Action("Index","Contact")" role="button">Create</a>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="btn-group pull-right">
                                                <button type="button" id="btnView" style="display:none;" class="btn btn-success btn-sm">View</button>
                                                <button type="button" id="btnEdit" style="display:none;" class="btn btn-warning btn-sm">Edit</button>
                                                <button type="button" id="btnViewCompany" style="display:none;" class="btn btn-primary btn-sm"> company </button>
                                                <button type="button" id="btnSellProduct" style="display:none;" class="btn btn-primary btn-sm">Sells products</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.tab-pane -->


                        <div class="tab-pane" id="tab_2">
                            <br />
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="txtCustomerName">Suppliers name</label>
                                        <input type="text" class="form-control" id="txtCustomerName" placeholder="Enter suppliers name">
                                    </div>
                                </div>
                            </div>

                            <div class="box-footer">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group pull-left">
                                            <button type="submit" id="btnSearch" class="btn btn-success btn-sm">Search</button>
                                            <button type="button" id="btnAdvanceSearch" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">Advance search</button>
                                            <a class="btn btn-primary btn-sm" href="@Url.Action("Index","Contact")" role="button">Create suppliers contact</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- nav-tabs-custom -->
            </div>
        </div>
        <!-- Customer Search Ends -->

        <div class="row">
            <div class="col-md-12">
                <div class="box box-solid">
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-striped" id="tblcontact">
                            <tr id="subhead">
                                <th></th>
                                <th>Customer name</th>
                                <th>Contact name</th>
                                <th>Email  </th>
                                <th>Office landline 1</th>
                                <th>Office landline 2</th>
                                <th>Mobile 1</th>
                                <th>Mobile 2</th>
                                <th>DMU Status Role</th>
                            </tr>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <div class="pagination pagination-sm no-margin pull-right">
                            <ul></ul>
                        </div>
                        <div id="divSearchGridOverlay" class="overlay">
                            <i class="fa fa-refresh fa-spin"></i>
                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col (left) -->
        </div>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Advance search</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="txtCustomerName">Contact name</label>
                            <input type="text" class="form-control" id="txtCustomerName" placeholder="Enter customer name">
                        </div>
                        <div class="form-group">
                            <label>Designation</label>
                            <select class="form-control" id="drpDesignation">
                                <option>option 1</option>
                                <option>option 2</option>
                                <option>option 3</option>
                                <option>option 4</option>
                                <option>option 5</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-sm">Save changes</button>
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

Kusumgar/Views/PostLogin/CRM/Contact/View.cshtml
@model Kusumgar.Models.ContactViewModel
@using KusumgarBusinessEntities.Common

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  
    <section class="content">
        <div class="row ">
            <div class="col-md-12 ">
                <div class="btn-group pull-right">
                    @*<button class="btn-primary btn-sm btn-success" type="button" value="Printable View" id="btnPrintable_View">Printable View</button>*@
                    <button class="btn-primary btn-sm btn-success hidden-print " type="button" value="Print" id="btnPrint" onclick="window.print()"><span class="fa fa-print"></span></button>
                </div>
            </div>
        </div>
                @{Html.RenderPartial("_PrintableView", Model);}
</section>

</div>
<!-- /.content-wrapper -->
<script>
    $(function () {

        $("#btnPrintable_View").click(function () {

            $("#frmPrintable_Contact").attr("action", "/system/printable-view/Contact/" + $("#hdfContact_Id").val());

            $("#frmPrintable_Contact").attr("method", "POST");

            $("#frmPrintable_Contact").attr("target", "blank");

            $("#frmPrintable_Contact").submit();

        });
    });
</script>

Kusumgar/Views/PostLogin/CRM/Contact/_CustomFields.cshtml
@model Kusumgar.Models.ContactViewModel
@using KusumgarBusinessEntities.Common  
<script src="/Scripts/CRM/Event/custom_field_event.js"></script>
<script src="/Scripts/CRM/Method/custom_field_method.js"></script>
<script src="/Scripts/CRM/Validation/custom_field_validation.js"></script>
<form id="frmCustom_Fields">

    <input type="hidden" id="hdnContact_Custom_Field_Id">
    <div class="row">
        <div class="col-md-4">
            <input type="hidden" id="hdn_Contact_Custom_Field_Id">
            <div class="form-group">
                <label style="color: #333">Field name :</label>
                <input type="text" id="txtField_Name" class="form-control input-sm" name="Field_Name" placeholder="Enter field Name" />
            </div>

            <div class="form-group">
                <label style="color: #333">Field value :</label>
                <input type="text" id="txtField_Value" class="form-control input-sm" name="Field_Value" placeholder="Enter field value" />
                <!-- /.input group -->
            </div>

        </div>

        <div class="col-md-8 ">
            <table class="table table-hover" id="tblCustom_Fields">
                <tr>
                    <th>Field name</th>
                    <th>Field value</th>
                    <th style="min-width: 81px;">&nbsp; </th>
                </tr>
                @foreach (var item in Model.Contact.Contact_Custom_Fields_List)
                {

                    <tr id="cust_tr_@item.Contact_Custom_Field_Id">

                        <td>@item.Field_Name</td>
                        <td>@item.Field_Value</td>
                        <td>
                            <input type="hidden" class="hdn_Contact_Custom_Field_Id" value="@item.Contact_Custom_Field_Id">

                            <input type="hidden" class="Field_Name" value="@item.Field_Name">
                            <input type="hidden" class="Field_Value" value="@item.Field_Value">

                            <div class="btn-group pull-right">
                                <button type="button" id="btnEdit" class="btn btn-info btn-sm" onclick="EditCustomFields(@item.Contact_Custom_Field_Id)"><i class='fa fa-pencil-square-o'></i></button>
                                <button type="button" id="btnRemove" class="btn btn-danger btn-sm " onclick="RemoveCustomFields(@item.Contact_Custom_Field_Id)"><i class='fa fa-times'></i></button>
                            </div>
                        </td>
                    </tr>

                }
            </table>
        </div>
    </div>
    <div class="box-footer">
        <div class="btn-group">
            <button type="button" class="btn btn-success btn-sm" id="btnSaveCustomField">Save custom field</button>
            <a href="@Url.Action("Search","Contact")" id="btnCancel" class="btn btn-warning btn-sm" role="button">Cancel</a>
        </div>
    </div>

</form>